# Generated by Django 5.0.7 on 2024-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finish_at",
            field=models.DateTimeField(null=True),
        ),
    ]
